// Per-user deposit-address store. Each user gets a unique deposit address
// for every supported coin. Addresses are deterministic (derived from
// the user id + coin) so they remain stable across reloads and can be
// re-derived at any time. In a real product these would be generated by
// the wallet service; here we simulate a believable shape.

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

const SUPPORTED_COINS: Array<{
  symbol: string;
  name: string;
  network: string;
  fee: number;
  minDeposit: number;
  minWithdraw: number;
  decimals: number;
  color: string;
}> = [
  { symbol: 'BTC', name: 'Bitcoin', network: 'Bitcoin', fee: 0.0001, minDeposit: 0.0001, minWithdraw: 0.0002, decimals: 8, color: '#f7931a' },
  { symbol: 'ETH', name: 'Ethereum', network: 'Ethereum (ERC-20)', fee: 0.0015, minDeposit: 0.005, minWithdraw: 0.01, decimals: 6, color: '#627eea' },
  { symbol: 'USDT', name: 'Tether', network: 'Ethereum (ERC-20)', fee: 5, minDeposit: 10, minWithdraw: 20, decimals: 2, color: '#26a17b' },
  { symbol: 'USDC', name: 'USD Coin', network: 'Ethereum (ERC-20)', fee: 5, minDeposit: 10, minWithdraw: 20, decimals: 2, color: '#2775ca' },
  { symbol: 'BNB', name: 'BNB', network: 'BNB Smart Chain (BEP-20)', fee: 0.0005, minDeposit: 0.01, minWithdraw: 0.02, decimals: 6, color: '#f0b90b' },
  { symbol: 'SOL', name: 'Solana', network: 'Solana', fee: 0.01, minDeposit: 0.05, minWithdraw: 0.1, decimals: 6, color: '#9945ff' },
  { symbol: 'XRP', name: 'XRP', network: 'XRP Ledger', fee: 0.5, minDeposit: 10, minWithdraw: 20, decimals: 4, color: '#23292f' },
  { symbol: 'ADA', name: 'Cardano', network: 'Cardano', fee: 1, minDeposit: 5, minWithdraw: 10, decimals: 4, color: '#0033ad' },
  { symbol: 'DOGE', name: 'Dogecoin', network: 'Dogecoin', fee: 5, minDeposit: 50, minWithdraw: 100, decimals: 4, color: '#c2a633' },
  { symbol: 'TRX', name: 'TRON', network: 'TRON (TRC-20)', fee: 1, minDeposit: 10, minWithdraw: 20, decimals: 2, color: '#ff060a' },
  { symbol: 'AVAX', name: 'Avalanche', network: 'Avalanche C-Chain', fee: 0.005, minDeposit: 0.05, minWithdraw: 0.1, decimals: 6, color: '#e84142' },
  { symbol: 'MATIC', name: 'Polygon', network: 'Polygon', fee: 0.5, minDeposit: 5, minWithdraw: 10, decimals: 4, color: '#8247e5' },
  { symbol: 'DOT', name: 'Polkadot', network: 'Polkadot', fee: 0.1, minDeposit: 1, minWithdraw: 2, decimals: 4, color: '#e6007a' },
  { symbol: 'LINK', name: 'Chainlink', network: 'Ethereum (ERC-20)', fee: 0.5, minDeposit: 1, minWithdraw: 2, decimals: 4, color: '#2a5ada' },
  { symbol: 'LTC', name: 'Litecoin', network: 'Litecoin', fee: 0.01, minDeposit: 0.1, minWithdraw: 0.2, decimals: 6, color: '#a6a9aa' },
];

export interface CoinMeta {
  symbol: string;
  name: string;
  network: string;
  fee: number;
  minDeposit: number;
  minWithdraw: number;
  decimals: number;
  color: string;
}

interface WalletState {
  supported: CoinMeta[];
  addresses: Record<string, Record<string, string>>;
  getAddress: (userId: string, symbol: string) => string;
  getCoin: (symbol: string) => CoinMeta | undefined;
  listCoins: () => CoinMeta[];
}

const ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

function generateAddress(userId: string, symbol: string): string {
  const data = `${userId}::${symbol}::starai-wallet-v2`;
  let h = 2166136261;
  for (let i = 0; i < data.length; i += 1) {
    h ^= data.charCodeAt(i);
    h = (h * 16777619) >>> 0;
  }
  let out = '';
  let s = h;
  for (let i = 0; i < 44; i += 1) {
    s = (s * 1103515245 + 12345) >>> 0;
    out += ALPHABET[s % ALPHABET.length];
    if (i === 0) out += ALPHABET[(h >>> 8) % ALPHABET.length];
  }
  if (symbol === 'BTC') return 'bc1q' + out.slice(0, 38);
  if (symbol === 'ETH' || symbol === 'USDT' || symbol === 'USDC' || symbol === 'LINK') return '0x' + out.slice(0, 40);
  if (symbol === 'SOL') return out.slice(0, 44);
  if (symbol === 'XRP') return 'r' + out.slice(0, 33);
  if (symbol === 'DOGE') return 'D' + out.slice(0, 33);
  if (symbol === 'LTC') return 'ltc1q' + out.slice(0, 38);
  if (symbol === 'TRX') return 'T' + out.slice(0, 33);
  return out.slice(0, 34);
}

function safeStorage(): Storage {
  try {
    if (typeof window === 'undefined' || !window.localStorage) {
      // In-memory shim so the store still works when storage is unavailable.
      const memory = new Map<string, string>();
      return {
        getItem: (k) => memory.get(k) ?? null,
        setItem: (k, v) => { memory.set(k, v); },
        removeItem: (k) => { memory.delete(k); },
        clear: () => memory.clear(),
        key: () => null,
        get length() { return memory.size; },
      } as Storage;
    }
    const probe = '__starai_probe__';
    window.localStorage.setItem(probe, '1');
    window.localStorage.removeItem(probe);
    return window.localStorage;
  } catch {
    const memory = new Map<string, string>();
    return {
      getItem: (k) => memory.get(k) ?? null,
      setItem: (k, v) => { memory.set(k, v); },
      removeItem: (k) => { memory.delete(k); },
      clear: () => memory.clear(),
      key: () => null,
      get length() { return memory.size; },
    } as Storage;
  }
}

export const useWalletStore = create<WalletState>()(
  persist(
    (set, get) => ({
      supported: SUPPORTED_COINS,
      addresses: {},

      getAddress(userId, symbol) {
        const cached = get().addresses[userId]?.[symbol];
        if (cached) return cached;
        const addr = generateAddress(userId, symbol);
        set((state) => {
          const current = { ...(state.addresses[userId] ?? {}) };
          current[symbol] = addr;
          return { addresses: { ...state.addresses, [userId]: current } };
        });
        return addr;
      },

      getCoin(symbol) {
        return get().supported.find((c) => c.symbol === symbol.toUpperCase());
      },

      listCoins() {
        return get().supported;
      },
    }),
    {
      name: 'starai:wallet:addresses:v2',
      storage: createJSONStorage(() => safeStorage()),
      partialize: (state) => ({ addresses: state.addresses }),
    },
  ),
);
